package com.pnj.uts.ti.nurul_hasanah

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.fragment.app.Fragment
import com.pnj.uts.ti.nurul_hasanah.Adapter.BeritaAdapter
import com.pnj.uts.ti.nurul_hasanah.Data.DataBerita
import com.pnj.uts.ti.nurul_hasanah.databinding.FragmentBeritaBinding


class FragmentBerita : Fragment(R.layout.fragment_berita) {
    private lateinit var binding: FragmentBeritaBinding
    private lateinit var beritaList : ArrayList<DataBerita>

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for the fragment
        binding = FragmentBeritaBinding.inflate(inflater, container, false)

        // Initialize the data
        val gambarBerita = intArrayOf(
            R.drawable.berita1,
            R.drawable.berita2,
            R.drawable.berita3,
            R.drawable.berita4,
            R.drawable.berita5,
            R.drawable.berita6,
            R.drawable.berita7,
            R.drawable.berita8,
            R.drawable.berita9,
            R.drawable.berita10
        )

        val judulBerita = arrayOf(
            "Sivitas Akademika PNJ Gelar Upacara Peringatan Hari Pendidikan Nasional 2024",
            "PERWAKILAN TIK PNJ RAIH JUARA TERBAIK I PILMAPRES TINGKAT LLDIKTI WILAYAH III PROGRAM DIPLOMA",
            "Diskusi Pra-KMIPN VI Forum Ketua Jurusan Teknik Informatika dan Komputer Politeknik Nasional",
            "PERSIAPAN KARIR TALENTA DIGITAL TERBAIK 5.0 BAGI MAHASISWA JURUSAN TIK PNJ",
            "Satukan Tangan, Satukan Hati, dan Saling Memaaafkan: Acara Kuliah Umum dan Halal Bihalal di Politeknik Negeri Jakarta Bersama Prof. Dr. KH. Nasaruddin Umar, MA.",
            "AN EXPO 2023 Sukses Terlaksana di Alun-Alun Kota Depok",
            "JURUSAN TIK BERSAMA DENGAN KEMENKOMINFO MENYELENGGARAKAN KULIAH UMUM PENGENALAN METAVERSE DI INDONESIA (METAVERSE 101) BATCH 3",
            "SELAMAT DAN SUKSES KEPADA AWARDEE IISMA 2024 JURUSAN TIK",
            "Memahami Konsep dan Potensi Internet of Things (IoT) di Industri Melalui Kuliah Umum Prodi Teknik Multimedia Jaringan dan Prodi Teknik Komputer Jaringan",
            "Politeknik Negeri Jakarta"
        )

        val deskripsiBerita = arrayOf(
            "Depok, 02 Mei 2024 - Dengan penuh sukacita dan semangat, Sivitas Akademika Politeknik Negeri Jakarta berkumpul di Lapangan SPIRIT PNJ untuk melaksanakan upacara memperingati Hari Pendidikan Nasional pada Kamis (2/5) pukul 08.00 WIB. Dengan tema 'Bergerak Bersama, Lanjutkan Merdeka Belajar', upacara ini menjadi momentum penting untuk merenungkan makna sejati dari pendidikan. Melalui pergerakan bersama, kita membangun landasan bagi masa depan yang lebih cerah. Lanjutkan merdeka belajar menjadi semboyan yang menggema, mengingatkan bahwa kemerdekaan sejati hanya bisa diraih melalui ilmu pengetahuan dan pendidikan yang berkualitas. Rangkaian dimulai saat inspektur upacara memasuki lapangan upacara, pengibaran bendera Sang Merah Putih, menyanyikan lagu kebangsaan Indonesia Raya dan Mengheningkan Cipta, pembacaan teks Pancasila dan Pembukaan UUD 1945, Amanat inspektur upacara, pembacaan doa, hingga inspektur upacara meninggalkan lapangan. Seiring dengan penghormatan kepada para pahlawan pendidikan, upacara ini juga menjadi ajang untuk menghargai jasa-jasa mereka dalam membangun peradaban bangsa. Dengan penuh rasa syukur, kita berkomitmen untuk melanjutkan perjuangan mereka, menjadikan pendidikan sebagai tonggak utama dalam mencapai cita-cita dan kejayaan bersama.",
            "Prestasi membanggakan kembali diraih mahasiswa Jurusan Teknik Informatika dan Komputer (TIK) Politeknik Negeri Jakarta (PNJ). Pratama Varian Andika Parulian Siregar mahasiwa program studi Teknik Multimedia dan Jaringan (TMJ) angkatan 2022 mengulang prestasi yang sama mahasiswa Jurusan TIK PNJ pada tahun 2023, yaitu berhak tampil pada pemilihan mahasiswa berprestasi (Pilmapres) tingkat nasional sebagai perwakilan tingkat Lembaga Layanan Pendidikan Tinggi (LLDikti) Wilayah III. Pilmapres merupakan ajang talenta dan kompetisi mahasiswa yang diselenggarakan oleh Balai Pengembangan Talenta Indonesia (BPTI), Pusat Prestasi Nasional Kementerian Pendidikan, Kebudayaan, Riset dan Teknologi yang diadakan setiap tahunnya. Penyelenggaraan Pilmapres dimulai dengan seleksi tingkat perguruan tinggi dan dilanjutkan dengan seleksi tingkat wilayah dan terakhir tingkat nasional. Pratama dinobatkan sebagai juara terbaik I pada ajang pilmapres tingkat LLDikti wilayah III program diploma tahun 2024. Pemilihan mahasiswa berperestasi di tingkat wilayah Jakarta ini  dilaksanakan pada tanggal 6-7 Mei 2024 bertempat di Universitas Kristen Indonesia. Pada ajang pemilihan ini, LLDikti Wilayah III telah menseleksi dan menghasilkan 5 mahasiswa berprestasi program sarjana dan 3 mahasiswa berprestasi program diploma untuk mengikuti pilmapres tingkat nasional tahun 2024 yang rencananya akan diselenggarakan pada tanggal 24-28 Juli 2024 di Gorontalo. Dan berikut daftar mahasiswa yang berhak mengikuti pilmapres tingkat nasional mewakili LLDIkti Wilyah III.",
            "Kompetisi Mahasiswa Informatika Politeknik Nasional (KMIPN) merupakan ajang perlombaan tahunan bagi institusi perguruan tinggi vokasi di bidang informatika. KMIPN tahun ini memasuki penyelenggaraan ke-VI dengan mengusung tema 'Inovasi Vokasi untuk Tren Informatika Masa Depan' dan akan dilaksanakan pada tanggal 1-3 Juli 2024. Tahun ini Politeknik Negeri Jakarta berkesempatan menjadi tuan rumah untuk ajang bergengsi ini dan seluruh persiapan sedang dilaksanakan demi suksesnya rangkaian kegiatan ajang KMIPN ke-VI nanti. Salah satunya adalah dengan menggelar Diskusi Pra-KMIPN VI yang dihadiri oleh Forum Ketua Jurusan Teknik Informatika dan Komputer Politeknik Nasional se-Indonesia. Forum diskusi yang dilaksanakan pada tanggal 6-8 Mei 2024 di Hotel Bumi Wiyata Depok ini dihadiri oleh sebanyak 15 Ketua Jurusan TIK Politeknik-Politeknik Nasional dari Sumatera hingga ujung Papua. Mereka sangat antusias dalam membahas segala persiapan perencanaan kegiatan KMIPN, termasuk perumusan buku panduan finalis serta survei lokasi kegiatan lomba. Acara ini dibuka oleh Ketua Badan Koordinasi Kemahasiswaan (Bakorma) Politeknik Se-Indonesia, Bapak Wahyu Kurnia Dewanto, S.Kom, M.T. dari Politeknik Negeri Jember sekaligus memberikan arahan mengenai kegiatan KMIPN dan Pusat Prestasi Nasional (Puspresnas). Dalam arahannya, beliau menyampaikan pentingnya kurasi talenta dengan tujuan untuk memberikan pengakuan resmi oleh pemerintah sehingga bermanfaat bagi peserta didik, penyelenggara ajang, dan pemerintah. KMIPN nantinya juga diharapkan dapat memunculkan satu mata lomba baru yang bisa dibidik untuk diinternasionalkan serta selalu up-to-date dengan perkembangan teknologi dan zaman untuk menuju World Skills Competition. Selain itu, penting juga adanya penjaminan mutu (quality control) dengan koordinasi yang maksimal dari semua pihak agar KMIPN ini nantinya tetap terus berlangsung dengan baik dan berkelanjutan sebagai ajang bergengsi untuk Politeknik se-Indonesia di bidang Informatika.",
            "Pada awal perkuliahan semester genap 2023/2024 tepatnya di minggu kedua, tanggal 20 Maret 2024, Jurusan Teknik Informatika dan Komputer (TIK) Politeknik Negeri Jakarta (PNJ) mengadakan Kuliah Umum (Kulum) bagi mahasiswa Program Studi Teknik Informatika (TI) dan Program Studi Teknik Multimedia Digital (TMD) yang diadakan di auditorium perpustakaan Politeknik Negeri Jakarta. Kegiatan kuliah umum ini diawali dengan sambutan oleh Ketua Program Studi Teknik Informatika, Euis Oktavianti, S.Si., M.T.I.,  yang mengucapkan terima kasih kepada para narasumber yang hadir dalam acara Kuliah Umum Program Studi TI dan TMD Tahun 2024 ini dengan tema “Persiapan Karir Talenta Digital Terbaik 5.0”. Tak lupa juga Ibu Euis menyampaikan terima kasih kepada para mahasiswa semester 2, 4, 6, dan 8 yang sudah menyempatkan hadir. Dalam sambutannya Ibu Euis juga menjelaskan kuliah umum ini bukan hanya merupakan agenda rutin setiap semester bagi program studi di Jurusan TIK. Tetapi juga ingin mengetahui update yang terjadi di industri untuk mempersiapkan diri dalam menghadapi tantangan masa depan karir di dunia IT, “karena perkembangnya sangat cepat sekali, jika kita tidak mengikuti atau membackup teknologi maka kita akan tertinggal” ujar Ibu Euis. Di akhir sambutannya Beliau juga mengajak kepada para mahasiswa yang hadir untuk menjadikan kuliah umum ini sebagai awal perjalanan karir untuk menjadi talenta digital terbaik Indonesia dan semoga sharing kenowledge yang akan diberikan para narasumber dapat memberikan nuansa dan wawasan baru bagi para peserta kuliah umum ini.",
            "Depok, 24 April 2024 - Politeknik Negeri Jakarta menggelar acara istimewa pada suasana hari yang fitri ini dengan mengundang Wakil Walikota Depok, Mitra PNJ, serta seluruh sivitas akademika untuk merayakan momen kebersamaan yang penuh makna yang diselenggarakan, bertempat di Auditorium Perpustakaan PNJ (24/4). Dalam semangat menyambut Idul Fitri, tema acara kali ini adalah 'Satukan Tangan, Satukan Hati, dan Saling Memaaafkan', sebuah panggilan untuk menjalin persatuan dan kebersamaan di antara kita. Acara dimulai dengan sambutan dari Dr. Titi Suhartati, SE, Ak., MM, MAk, CA, CPIA. selaku Wakil Direktur Bidang Keuangan dan Umum yang mewakili Direktur PNJ. Acara silaturahim ini PNJ gelar setiap tahun, sungguh merupakan kegiatan penting untuk bersilaturahim dan bermanfaat bagi kita semua untuk saling memaafkan atas segala kesalahan, kekhilafan selama berinteraksi, karena sebagai manusia kita tidak pernah luput dari kesalahan dan khilaf. Mewakili Pimpinan PNJ saya mengucapkan Selamat Hari Raya Idul Fitri Mohon maaf lahir dan batin, kami sampaikan apresiasi kepada seluruh pihak yang mendukung dan berpartisipasi dalam kegiatan Halal Bihalal PNJ 2024 semoga dicatat Allah SWT  sebagai amal saleh Aamiin Ya Robbal Alamin.' ujarnya.",
            "AN EXPO adalah acara tahunan yang berlangsung sejak tahun 1992, diselenggarakan oleh Mahasiswa Politeknik Negeri Jakarta Jurusan Administrasi Niaga Program Studi D3 Administrasi Bisnnis Semester 5. Pada tahun ini AN EXPO 2023 mengusung tema “ ANEXPISAN - Sang Maestro dan Legenda” dengan tagline “Mengubah Persepsi, Melestarikan Tradisi” dengan tujuan mengenalkan dan melestarikan salah satu budaya Nusantara yaitu Budaya Sunda, serta mengembangkam skill mahasiswa dalam berbisnis dan berkomunikasi serta mendorong pertumbuhan dan perkembangan pelaku UMKM. Kegiatan AN EXPO 2023 ini merealisasikan 3 mata kuliah yaitu Administrasi Penjualan, Bahasa Inggris Untuk Komunikasi, dan Perdagangan Elektronik. Rangkaian acara AN EXPO 2023 terbagi menjadi 3 rangkaian yaitu Babuka Carita (Pembuka Cerita), Dunya Pasundan (Dunia Persundaan), dan Paturay Tineung (Pesta Perpisahan). AN EXPO ini berlangsung dari tanggal 30 November – 02 Desember 2023 (Dunya Pasundan), dan 03 Desember 2023 (Paturay Tineung), selama Dunya Pasundan berlangsung berhasil menghadirkan 9.061 pengunjung baik dari internal Politeknik Negeri Jakarta dan juga eksternal Politeknik Negeri Jakarta. Dengan banyaknya pengunjung yang turut hadir di AN EXPO 2023 ini  membantu UMKM yang sedang berjualan. UMKM yang turut hadir dalam AN EXPO terdiri dari berbagai macam kategori diantaranya ada makanan, otomotif, bookstore, sport, peralatan rumah tangga, beauty care. Dengan beragamnya produk yang ditawarkan ini membuat masyarakat Depok untuk mengelilingi Alun-Alun dan berbelanja pada masing-masing tempat UMKM.",
            "Jurusan Teknik Informatika dan Komputer (TIK) Politeknik Negeri Jakarta bekerjasama dengan Kementerian Komunikasi dan Informatika dan WIR Group menyeleggarakan Pengenalan Metaverse di Indonesia (Metaverse 101) Batch 3. Kegiatan ini sekaligus merupakan pelaksanaan kuliah umum Program Studi Teknik Informatika Jurusan TIK. Dalam sambutannya Wakil Direktur Bidang Kerjasama Dr. Dewi Yanti Liliana, S. Kom., M. Kom. yang mewakili Direktur Politeknik Negeri Jakarta menyampaikan jajaran pimpinan Politeknik Negeri Jakarta mengucapkan terima kasih kepada semua pihak sehingga kegiatan Kuliah Umum Pengenalan Metaverse di Indonesia (Metaverse 101) Batch 3 ini dapat terselenggara. Beliau juga menyampaikan kuliah umum yang menghadirkan praktisi industri merupakan salah satu indikator kinerja utama perguruan tinggai yaitu indikator ke 4, sehingga pimpinan sangat mendukung dan memfasilitasi praktisi industri untuk mengajar di PNJ. Seperti diketahui praktisi industri merupakan orang yang memiliki pengalaman langsung di lapangan keilmuannya juga luas, sehingga sangat paham akan kondisi di lapangan. Kegiatan menghadirkan praktisi industri untuk mengajar langsung di perguruan tinggi merupakan salah satu series program merdeka belajar yang diinisiasi oleh Kemendikbud Ristek. Dengan adanya program merdeka belajar dapat membuka sekat-sekat di perguruan tinggi. Pada jaman dulu kuliah hanya belajar di dalam kampus bersama dosen, sekarang mahasiswa bisa berkesempatan belajar di luar kampus, dapat mengambil mata kuliah di luar program studi selama tiga semester, bahkan contohnya ada mahasiswa dari Jurusan Teknik Mesin yang mendaftar belajar di Jurusan TIK. “Sekali lagi PNJ berterima kasih kepada Kemenkominfo yang telah menghadirkan narasumber atau dosen dari praktisi industri, semoga kerjasama kedua belah pihak selanjutnya dalam memberikan kontribusi dapat dilanjutkan”, ujar Dewi Yanti.",
            "Berdasarkan pengumuman hasil resmi seleksi IISMA 2024, Poiteknik Negeri Jakarta berhasil meloloskan sebanyak 45 mahasiswa sebagai penerima beasiswa International Student Mobility Awards ( IISMA ) 2024 yang berasal dari 6 jurusan dan 15 program studi dengan tujuan 27 universitas dari 17 negara. Hal yang sangat membanggakan Jurusan Teknik Informatika dan Komputer (TIK) pada edisi IISMA 2024 berhasil meloloskan 17 mahasiswanya sebagai AWARDEE IISMA 2024, jumlah ini merupakan yang terbanyak diantara Jurusan lain di Politeknik Negeri Jakarta. Penerima beasiswa IISMA 2024 Jurusan Teknik Mesin (2 mahasiswa),  Teknik Elektro (3 mahasiswa), Akutansi (3 mahasiswa), Administrasi Niaga (12 mahasiswa) dan Teknik Grafika dan Penerbitan (8 mahasiswa). Dari 17 mahasiswa awardee IISMA 2024 Jurusan TIK tersebar di 3 Program Studi (Prodi) yaitu  8 mahasiswa berasal dari Prodi Teknik informatika (TI), 2 mahasiswa Prodi Teknik Multimedia dan Jaringan (TMJ) dan 7 mahasiswa Prodi Teknik Multimedia Digital (TMD). Setiap tahunya mahasiswa Jurusan TIK yang lolos sebagai penerima beasiswa IISMA selalu meningkat, pada tahun 2022 sebanyak 2 mahasiswa dan pada tahun 2023 sebanyak 6 mahasiswa. Pada tahun 2024 tujuan universitas yang dipilih mahasiswa Jurusan TIK tersebar di 10 perguruan tinggi di 8 negara yaitu Korea Selatan, Taiwan, Australia, USA, Belanda, UK, Portugal dan Polandia.",
            "Internet of Things (IoT) menggunakan pemrograman untuk menghasilkan interaksi antar mesin tanpa campur tangan manusia. Interaksi tersebut memanfaatkan konektivitas internet yang tersambung secara terus-menerus. Komunikasi antar mesin atau benda yang menggunakan teknologi IoT dapat berupa pertukaran data atau pengendalian jarak jauh. Teknologi tersebut juga menjadi pendukung utama pembangunan kota pintar atau smart city. Dalam era digital yang semakin maju saat ini, IoT telah menjadi topik yang hangat dan menarik perhatian banyak pihak. Konsep ini memungkinkan perangkat elektronik dan benda-benda sehari-hari untuk saling terhubung dan berkomunikasi serta membuka peluang baru dalam berbagai bidang industri. Oleh karena itu, Prodi D4 Teknik Multimedia Jaringan dan Prodi D1 Teknik Komputer Jaringan membuat kegiatan Kuliah Umum dengan judul “Transformasi Digital” dan “Teknologi Jaringan Sensor” pada tanggal 6 Oktober 2023 di Aula Gedung Serba Guna dengan pembicara Faizal Hasby dari Best-Path Network dan dari PT. Knockthing Benda Pintar.",
            "Politeknik Negeri Jakarta /Politeknik UI adalah salah satu perguruan tinggi negeri politeknik berstatus Badan Layanan Umum yang terdapat di areal kampus Universitas Indonesia, Depok, Jawa Barat, Indonesia. \nAlamat: Universitas Indonesia, Jl. Prof. DR. G.A. Siwabessy, Kukusan, Beji, Depok City, West Java 16425\nDidirikan: 22 September 1982\nKampus: Urban\nDirektur: Dr. Syamsurizal, S.E, M.M\nProvinsi: Jawa Barat\nWarna: Kuning\nTelepon: (021) 7270036\nJenis: Perguruan Tinggi Negeri\nMoto: Menjadi Politeknik Unggul Bertaraf Internasional Untuk Mendukung Daya Saing Bangsa\nNama julukan: PNJ\nNama sebelumnya: - Politeknik Universitas Indonesia (1982); - Fakultas Non-Gelar Teknologi Universitas Indonesia(1975)"
        )

        beritaList = ArrayList()
        for (i in gambarBerita.indices) {
            val berita = DataBerita(judulBerita[i], deskripsiBerita[i], gambarBerita[i])
            beritaList.add(berita)
        }



        // Return the root view of the fragment
        return binding.root
    }
}